version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/library"
    volumes:
      - ./backend:/app  # Mount the backend directory for live code reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  # Next.js Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

# Define a volume for PostgreSQL data persistence
volumes:
  postgres_data:
